{% set name = "aws-lambda-powertools" %}
{% set version = "2.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws_lambda_powertools-{{ version }}.tar.gz
  sha256: e4f4eb92ae1298ad34ae8b9738be4d089ca8413ae16189022aa8a4c8b36ea4c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.3.2
    - python >=3.7.4,<4.0
  run:
    - typing-extensions >=4.4.0,<5.0.0
    - python >=3.7.4,<4.0
    - aws-xray-sdk >=2.8.0,<3.0.0
    - pydantic >=1.8.2,<2.0.0
    - boto3 >=1.20.32,<1.21
    - python-fastjsonschema >=2.14.5,<3.0.0
    - boto3

test:
  imports:
    - aws_lambda_powertools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://awslabs.github.io/aws-lambda-powertools-python/
  summary: Python utilities for AWS Lambda functions including but not limited to tracing, logging and custom metric
  description: |
    A suite of Python utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging,
    custom metrics, and more. ([AWS Lambda Powertools Java](https://github.com/awslabs/aws-lambda-powertools-java) is also available).
  license: MIT-0 AND Apache-2.0
  license_family: MIT
  license_file:
    - LICENSE
    - THIRD-PARTY-LICENSES
  doc_url: https://awslabs.github.io/aws-lambda-powertools-python/api/
  dev_url: https://github.com/awslabs/aws-lambda-powertools-python

extra:
  recipe-maintainers:
    - BastianZim
