{% set name = "aws-lambda-powertools" %}
{% set version = "3.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_lambda_powertools-{{ version }}.tar.gz
  sha256: 99dc11ac6eb81564f599fdd85ba79069f7740ae3481c99bca2cee8abb7c95543

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.3.2
    - pip
  run:
    - typing_extensions >=4.11.0,<5.0.0
    - jmespath >=1.0.1,<2.0.0
    - python >={{ python_min }},<4.0.0
    - typing-extensions >=4.11.0,<5.0.0
# Extra: parser
    - pydantic >=2.0.3,<2.1
# Extra: tracer
    - aws-xray-sdk >=2.8.0,<3.0.0
# Extra: validation
    - python-fastjsonschema >=2.14.5,<3.0.0
# Extra: aws-sdk
    - boto3 >=1.34.32,<2.0.0
# Extra: datamasking
    - aws-encryption-sdk >=3.1.1,<5.0.0
    - jsonpath-ng >=1.6.0,<2
# Extra: redis
    - redis-py >=4.4,<6.0
  run_constrained:
    - datadog-lambda >=4.77,<7.0
    # Proprietary software

test:
  imports:
    - aws_lambda_powertools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://awslabs.github.io/aws-lambda-powertools-python/
  summary: Python utilities for AWS Lambda functions including but not limited to tracing, logging and custom metric
  description: |
    A suite of Python utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging,
    custom metrics, and more. ([AWS Lambda Powertools Java](https://github.com/awslabs/aws-lambda-powertools-java) is also available).
  license: MIT-0 AND Apache-2.0
  license_family: MIT
  license_file:
    - LICENSE
    - THIRD-PARTY-LICENSES
  doc_url: https://awslabs.github.io/aws-lambda-powertools-python/api/
  dev_url: https://github.com/awslabs/aws-lambda-powertools-python

extra:
  recipe-maintainers:
    - BastianZim
