{% set name = "aws-lambda-powertools" %}
{% set version = "2.29.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws_lambda_powertools-{{ version }}.tar.gz
  sha256: 5d6f2d5c7c34dab313cdd57115da83b0093e72359c326414e51e6c9206eda0f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7.4,<4.0
    - poetry-core >=1.3.2
    - pip
  run:
    - python >=3.7.4,<4.0.0
    - typing-extensions >=4.6.2,<5.0.0
# Extra: parser
    - pydantic >=1.8.2,<2.0.0
# Extra: tracer
    - aws-xray-sdk >=2.8.0,<3.0.0
# Extra: validation
    - python-fastjsonschema >=2.14.5,<3.0.0
# Extra: aws-sdk
    - boto3 >=1.20.32,<2.0.0
# Extra: datamasking-aws-sdk
    - aws-encryption-sdk >=3.1.1,<4.0.0
  run_constrained:
    - datadog-lambda >=4.77,<6.0
    # Proprietary software

test:
  imports:
    - aws_lambda_powertools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://awslabs.github.io/aws-lambda-powertools-python/
  summary: Python utilities for AWS Lambda functions including but not limited to tracing, logging and custom metric
  description: |
    A suite of Python utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging,
    custom metrics, and more. ([AWS Lambda Powertools Java](https://github.com/awslabs/aws-lambda-powertools-java) is also available).
  license: MIT-0 AND Apache-2.0
  license_family: MIT
  license_file:
    - LICENSE
    - THIRD-PARTY-LICENSES
  doc_url: https://awslabs.github.io/aws-lambda-powertools-python/api/
  dev_url: https://github.com/awslabs/aws-lambda-powertools-python

extra:
  recipe-maintainers:
    - BastianZim
