schema_version: 1

context:
  name: aws-lambda-powertools
  version: 3.19.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/aws_lambda_powertools-${{ version }}.tar.gz
  sha256: 8897ba4be0b3a51f2b8f68946d650f3ef574fa2c40395544de03bd0c61979999

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.3.2
    - pip
  run:
    - typing_extensions >=4.11.0,<5.0.0
    - jmespath >=1.0.1,<2.0.0
    - python >=${{ python_min }},<4.0.0
    - typing-extensions >=4.11.0,<5.0.0
    # Extra: parser
    - pydantic >=2.0.3,<2.1
    # Extra: tracer
    - aws-xray-sdk >=2.8.0,<3.0.0
    # Extra: validation
    - python-fastjsonschema >=2.14.5,<3.0.0
    # Extra: aws-sdk
    - boto3 >=1.34.32,<2.0.0
    # Extra: datamasking
    - aws-encryption-sdk >=3.1.1,<5.0.0
    - jsonpath-ng >=1.6.0,<2
    # Extra: afka-consumer-avro
    - avro >=1.12.0,<2
    # Extra: redis
    - redis-py >=4.4,<7.0
  run_constraints:
    - datadog-lambda >=4.77,<7.0
    - valkey-glide >=1.3.5,<3.0
    - protobuf >=6.30.2,<6.40

tests:
  - python:
      imports:
        - aws_lambda_powertools
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Python utilities for AWS Lambda functions including but not limited to tracing, logging and custom metric
  description: |
    A suite of Python utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging,
    custom metrics, and more. ([AWS Lambda Powertools Java](https://github.com/awslabs/aws-lambda-powertools-java) is also available).
  license: MIT-0 AND Apache-2.0
  license_file:
    - LICENSE
    - THIRD-PARTY-LICENSES
  homepage: https://awslabs.github.io/aws-lambda-powertools-python/
  repository: https://github.com/awslabs/aws-lambda-powertools-python
  documentation: https://awslabs.github.io/aws-lambda-powertools-python/api/

extra:
  recipe-maintainers:
    - BastianZim
